name: CI

on:
  push:
  pull_request:

jobs:
  test_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: create env
      run: bin/hatch run dev-compiled:uv-pip-install

    - name: run pytest
      run: bin/hatch run dev-compiled:pytest
