name: CI

on:
  push:
  pull_request:

jobs:
  test_matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            hatch: bin/hatch
          - os: windows-2022
            hatch: bin/hatch.exe
          - os: macos-14
            hatch: bin/hatch.command

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: create env
      run: ${{ matrix.hatch }} run dev-compiled:uv-pip-install

    - name: run pytest
      run: ${{ matrix.hatch }} run dev-compiled:pytest
